name: CI/CD Pipeline for FastAPI

on:
  push:
    branches:
      - main  # Exécutez le pipeline lorsqu'il y a un push sur la branche principale.
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Vérifier le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurer Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construire et taguer l'image Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/api:latest .

      # 4. Pousser l'image vers Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/api:latest

      # 5. Déployer sur un serveur distant via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
            docker stop fastapi-container || true
            docker rm fastapi-container || true
            docker run -d --name fastapi-container -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
